// Situations ajoutées en phase 1 bis : vie pratique, séries, voyage, carrière. Même format que dans data.js.

export const EXTRA_CHARACTERS = {
  carla: { name: "Carla", role: "Caissière", emoji: "🛒", color: "#E11D48" },
  jay: { name: "Jay", role: "Coach sportif", emoji: "🏋️", color: "#EA580C" },
  mo: { name: "Mo", role: "Coiffeur", emoji: "💇", color: "#7C3AED" },
  diaz: { name: "Officer Diaz", role: "Policière", emoji: "🚨", color: "#1D4ED8" },
  grace: { name: "Grace", role: "Agente à l'aéroport", emoji: "🛫", color: "#0891B2" },
  ben: { name: "Ben", role: "Steward", emoji: "✈️", color: "#2563EB" },
  daniel: { name: "Daniel", role: "Conseiller bancaire", emoji: "🏦", color: "#15803D" },
  olivia: { name: "Olivia", role: "Recruteuse", emoji: "🤝", color: "#BE185D" },
  raj: { name: "Raj", role: "Rencontré à un salon pro", emoji: "🏢", color: "#B45309" },
  steve: { name: "Steve", role: "Un client", emoji: "📧", color: "#475569" },
};

export const EXTRA_SITUATIONS = [
  // ---------- Vie pratique ----------
  {
    id: "supermarket",
    char: "carla",
    emoji: "🛒",
    title: "Au supermarché",
    intro: "À la caisse, ce sont presque toujours les mêmes questions : sac, carte de fidélité, paiement. Aux États-Unis, on te demande souvent « Did you find everything okay? ».",
    phrases: [
      { en: "Where can I find the eggs?", fr: "Où est-ce que je peux trouver les œufs ?" },
      { en: "Which aisle is it in?", fr: "C'est dans quel rayon ?", note: "« Aisle » se prononce « aïl » (le s est muet) : c'est l'allée, le rayon." },
      { en: "Do you have a rewards card?", fr: "Vous avez une carte de fidélité ?" },
      { en: "No, I don't.", fr: "Non, je n'en ai pas." },
      { en: "Paper or plastic?", fr: "Sac en papier ou en plastique ?" },
      { en: "Can I pay with my phone?", fr: "Je peux payer avec mon téléphone ?" },
      { en: "Do you want your receipt?", fr: "Vous voulez votre ticket ?" },
      { en: "Sorry, I forgot something.", fr: "Pardon, j'ai oublié un truc." },
    ],
    dialogue: {
      title: "À la caisse",
      turns: [
        { them: "Hi! Did you find everything okay?", fr: "Bonjour ! Vous avez trouvé tout ce qu'il vous fallait ?" },
        { you: "Réponds oui, mais demande où trouver les œufs.", answers: ["Yes, but where can I find the eggs?", "Yes, thanks. Where can I find the eggs?"] },
        { them: "Aisle five, on the left.", fr: "Rayon 5, à gauche." },
        { you: "Tu reviens à la caisse : dis « pardon, j'ai oublié un truc ».", answers: ["Sorry, I forgot something."] },
        { them: "No problem! Do you have a rewards card?", fr: "Pas de souci ! Vous avez une carte de fidélité ?" },
        { you: "Réponds non, et demande si tu peux payer avec ton téléphone.", answers: ["No, I don't. Can I pay with my phone?"] },
        { them: "Sure. Do you want your receipt?", fr: "Bien sûr. Vous voulez votre ticket ?" },
        { you: "Refuse poliment.", answers: ["No, I'm good, thanks.", "I'm good, thanks."] },
      ],
    },
  },
  {
    id: "gym",
    char: "jay",
    emoji: "🏋️",
    title: "À la salle de sport",
    intro: "À la salle, on demande si une machine est libre avec « Are you using this? ». Et le coach crie « One more! » pour te motiver.",
    phrases: [
      { en: "Are you using this?", fr: "Vous utilisez ça ?", note: "Pour savoir si une machine est libre." },
      { en: "I'm new here.", fr: "Je suis nouveau (nouvelle) ici." },
      { en: "How do I use this machine?", fr: "Comment on utilise cette machine ?" },
      { en: "How many sets left?", fr: "Il te reste combien de séries ?" },
      { en: "One more!", fr: "Encore une !" },
      { en: "I'm out of shape.", fr: "Je ne suis pas en forme.", note: "Littéralement « hors de forme » : pas en condition physique." },
      { en: "My legs are killing me.", fr: "J'ai super mal aux jambes.", note: "« … is killing me » = me fait très mal, ou m'épuise." },
      { en: "Good workout!", fr: "Bonne séance !" },
    ],
    dialogue: {
      title: "Premier jour à la salle",
      turns: [
        { them: "Hey! First time here?", fr: "Salut ! C'est ta première fois ici ?" },
        { you: "Dis oui, tu es nouveau (nouvelle) ici, et tu n'es pas en forme.", answers: ["Yeah, I'm new here. I'm out of shape.", "Yes, I'm new here, and I'm out of shape."] },
        { them: "No worries, everyone starts somewhere!", fr: "Pas de souci, tout le monde commence un jour !" },
        { you: "Demande comment on utilise cette machine.", answers: ["How do I use this machine?"] },
        { them: "Like this. Ten reps… Come on, one more!", fr: "Comme ça. Dix répétitions… Allez, encore une !" },
        { you: "Dis que tu as super mal aux jambes !", answers: ["My legs are killing me!"] },
        { them: "Haha, that means it's working! Good workout!", fr: "Haha, ça veut dire que ça marche ! Bonne séance !" },
        { you: "Remercie-le beaucoup.", answers: ["Thanks a lot!", "Thank you so much!"] },
      ],
    },
  },
  {
    id: "haircut",
    char: "mo",
    emoji: "💇",
    title: "Chez le coiffeur",
    intro: "Chez le coiffeur, on dit ce qu'on veut simplement : « Just a trim » (juste rafraîchir), « shorter on the sides » (plus court sur les côtés).",
    phrases: [
      { en: "Do you take walk-ins?", fr: "Vous prenez sans rendez-vous ?" },
      { en: "Just a trim, please.", fr: "Juste rafraîchir, s'il vous plaît.", note: "« A trim » = couper un peu, rafraîchir la coupe." },
      { en: "A little shorter on the sides.", fr: "Un peu plus court sur les côtés." },
      { en: "Not too short, please.", fr: "Pas trop court, s'il vous plaît." },
      { en: "Can you take a bit more off the top?", fr: "Vous pouvez couper un peu plus sur le dessus ?" },
      { en: "It looks great, thanks!", fr: "C'est super, merci !" },
      { en: "How much do I owe you?", fr: "Je vous dois combien ?" },
      { en: "Can I book my next appointment?", fr: "Je peux prendre mon prochain rendez-vous ?" },
    ],
    dialogue: {
      title: "Tu entres chez un coiffeur",
      turns: [
        { you: "Demande s'ils prennent sans rendez-vous.", answers: ["Do you take walk-ins?", "Hi, do you take walk-ins?"] },
        { them: "Sure, have a seat! What are we doing today?", fr: "Bien sûr, asseyez-vous ! On fait quoi aujourd'hui ?" },
        { you: "Dis : juste rafraîchir, pas trop court.", answers: ["Just a trim, please. Not too short.", "Just a trim. Not too short, please."] },
        { them: "Got it. A little shorter on the sides?", fr: "C'est noté. Un peu plus court sur les côtés ?" },
        { you: "Dis oui, un peu plus court sur les côtés.", answers: ["Yes, a little shorter on the sides.", "Yeah, a little shorter on the sides."] },
        { them: "All done! What do you think?", fr: "Et voilà ! Vous en pensez quoi ?" },
        { you: "Dis que c'est super, et demande combien tu dois.", answers: ["It looks great, thanks! How much do I owe you?"] },
        { them: "Twenty-five dollars. See you next time!", fr: "25 dollars. À la prochaine !" },
      ],
    },
  },
  {
    id: "emergency",
    char: "diaz",
    emoji: "🚨",
    title: "Un problème à signaler",
    intro: "Si on te vole ton téléphone ou ton portefeuille, va au commissariat (« police station »). Numéro d'urgence : 911 aux États-Unis, 999 au Royaume-Uni. Reste simple : quoi, où, quand.",
    phrases: [
      { en: "I need help.", fr: "J'ai besoin d'aide." },
      { en: "Someone stole my wallet.", fr: "Quelqu'un a volé mon portefeuille." },
      { en: "I lost my passport.", fr: "J'ai perdu mon passeport." },
      { en: "It happened an hour ago.", fr: "C'est arrivé il y a une heure." },
      { en: "It was on the subway.", fr: "C'était dans le métro." },
      { en: "I need a police report.", fr: "J'ai besoin d'un rapport de police.", note: "Souvent demandé par les assurances." },
      { en: "Call an ambulance!", fr: "Appelez une ambulance !" },
      { en: "Where's the French embassy?", fr: "Où est l'ambassade de France ?" },
    ],
    dialogue: {
      title: "Au commissariat",
      turns: [
        { them: "Hi, what can I do for you?", fr: "Bonjour, je peux faire quelque chose pour vous ?" },
        { you: "Dis que quelqu'un a volé ton portefeuille.", answers: ["Someone stole my wallet.", "Hi, someone stole my wallet."] },
        { them: "I'm sorry. When did it happen?", fr: "Je suis désolée. Quand est-ce que c'est arrivé ?" },
        { you: "Dis que c'est arrivé il y a une heure, dans le métro.", answers: ["It happened an hour ago. It was on the subway.", "It happened an hour ago, on the subway."] },
        { them: "Okay. Did you lose anything else?", fr: "D'accord. Vous avez perdu autre chose ?" },
        { you: "Dis que tu as aussi perdu ton passeport.", answers: ["I lost my passport too.", "I lost my passport."] },
        { them: "Then you'll need to contact your embassy.", fr: "Alors il faudra contacter votre ambassade." },
        { you: "Demande un rapport de police, et où est l'ambassade de France.", answers: ["I need a police report. Where's the French embassy?"] },
        { them: "Here's your report. The embassy is on Fifth Avenue.", fr: "Voici votre rapport. L'ambassade est sur la Cinquième Avenue." },
      ],
    },
  },

  // ---------- Comme dans les séries ----------
  {
    id: "series1",
    char: "sam",
    emoji: "🎬",
    title: "Répliques de séries",
    intro: "Ces répliques reviennent dans toutes les séries américaines. Une fois que tu les connais, tu les entends partout !",
    phrases: [
      { en: "Are you kidding me?", fr: "Tu te moques de moi ?", note: "Pour la surprise ou l'agacement." },
      { en: "What's going on?", fr: "Qu'est-ce qui se passe ?" },
      { en: "Calm down.", fr: "Calme-toi." },
      { en: "Trust me.", fr: "Fais-moi confiance." },
      { en: "I've got this.", fr: "Je gère.", note: "Pour encourager quelqu'un : « You got this! » (tu vas y arriver)." },
      { en: "Give me a break.", fr: "Lâche-moi un peu." },
      { en: "We need to talk.", fr: "Il faut qu'on parle." },
      { en: "It's not what it looks like!", fr: "Ce n'est pas ce que tu crois !" },
    ],
    dialogue: {
      title: "Sam débarque chez toi en panique",
      turns: [
        { them: "Dude, open the door! Quick!", fr: "Mec, ouvre la porte ! Vite !" },
        { you: "Demande ce qui se passe.", answers: ["What's going on?"] },
        { them: "I locked myself out and my phone is dead!", fr: "Je me suis enfermé dehors et mon téléphone n'a plus de batterie !" },
        { you: "Dis-lui de se calmer : tu gères.", answers: ["Calm down. I've got this."] },
        { them: "Are you sure? Can you call a locksmith?", fr: "T'es sûr ? Tu peux appeler un serrurier ?" },
        { you: "Dis : fais-moi confiance.", answers: ["Trust me."] },
        { them: "Okay… Wait. The door was open the whole time!", fr: "OK… Attends. La porte était ouverte depuis le début !" },
        { you: "Réagis : tu te moques de moi ?", answers: ["Are you kidding me?"] },
        { them: "Haha, give me a break, it's been a long day!", fr: "Haha, lâche-moi un peu, j'ai eu une longue journée !" },
      ],
    },
  },
  {
    id: "series2",
    char: "nina",
    emoji: "📺",
    title: "Réactions de séries",
    intro: "Encore des expressions de séries, pour réagir comme un vrai personnage. Attention au ton : « Shut up! » entre amis veut souvent dire « pas possible ! ».",
    phrases: [
      { en: "Oh my God!", fr: "Oh mon Dieu !", note: "Souvent écrit « OMG » par texto." },
      { en: "Shut up!", fr: "Arrête, sérieux ?!", note: "Entre amis, ça veut souvent dire « pas possible ! », pas « tais-toi ». Tout est dans le ton." },
      { en: "I'm so done.", fr: "J'en peux plus." },
      { en: "That's so annoying.", fr: "C'est trop énervant." },
      { en: "Let me guess.", fr: "Laisse-moi deviner." },
      { en: "Busted!", fr: "Grillé !", note: "Quand on prend quelqu'un la main dans le sac." },
      { en: "I'll explain later.", fr: "Je t'expliquerai plus tard." },
      { en: "Deal with it.", fr: "Fais avec.", note: "Un peu sec : à utiliser avec humour." },
    ],
    dialogue: {
      title: "Ta coloc te surprend en train de manger son gâteau",
      turns: [
        { them: "Hey! Is that my cake?", fr: "Hé ! C'est mon gâteau ?" },
        { you: "Dis : je t'expliquerai plus tard !", answers: ["I'll explain later!"] },
        { them: "Busted! Let me guess… you were starving?", fr: "Grillé ! Laisse-moi deviner… tu mourais de faim ?" },
        { you: "Avoue : oui, tu meurs de faim !", answers: ["Yes, I'm starving!", "Yeah, I'm starving!"] },
        { them: "Oh my God, you ate half of it!", fr: "Oh mon Dieu, t'en as mangé la moitié !" },
        { you: "Fais une blague : fais avec !", answers: ["Deal with it!"] },
        { them: "Shut up! You're so annoying, haha.", fr: "Arrête ! T'es trop énervant(e), haha." },
      ],
    },
  },

  // ---------- Voyage ----------
  {
    id: "airport",
    char: "grace",
    emoji: "🛫",
    title: "À l'aéroport",
    intro: "À l'aéroport, tout va vite : l'enregistrement (« check-in »), le contrôle de sécurité (« security »), la porte d'embarquement (« gate »). Garde « Sorry, what? » sous la main !",
    phrases: [
      { en: "Where do I check in?", fr: "Où est-ce que je m'enregistre ?" },
      { en: "I have one bag to check.", fr: "J'ai un bagage à enregistrer." },
      { en: "Can I take this on the plane?", fr: "Je peux prendre ça dans l'avion ?" },
      { en: "Window or aisle?", fr: "Hublot ou couloir ?", note: "« Aisle » se prononce « aïl »." },
      { en: "Aisle, please.", fr: "Couloir, s'il vous plaît." },
      { en: "Which gate is it?", fr: "C'est quelle porte ?" },
      { en: "Is the flight on time?", fr: "Le vol est à l'heure ?" },
      { en: "My flight is delayed.", fr: "Mon vol est retardé." },
    ],
    dialogue: {
      title: "Enregistrement au comptoir",
      turns: [
        { them: "Hi! Passport, please. Any bags to check?", fr: "Bonjour ! Passeport, s'il vous plaît. Des bagages à enregistrer ?" },
        { you: "Dis que tu as un bagage à enregistrer.", answers: ["I have one bag to check.", "Yes, I have one bag to check."] },
        { them: "Great. Window or aisle?", fr: "Parfait. Hublot ou couloir ?" },
        { you: "Choisis le couloir.", answers: ["Aisle, please."] },
        { them: "Here's your boarding pass.", fr: "Voici votre carte d'embarquement." },
        { you: "Demande quelle est la porte, et si le vol est à l'heure.", answers: ["Which gate is it? Is the flight on time?"] },
        { them: "Gate twelve. And yes, it's on time. Have a good flight!", fr: "Porte 12. Et oui, il est à l'heure. Bon vol !" },
      ],
    },
  },
  {
    id: "plane",
    char: "ben",
    emoji: "✈️",
    title: "Dans l'avion",
    intro: "À bord, le personnel est souvent très détendu. Pour demander quelque chose, « Could I get… ? » marche à tous les coups.",
    phrases: [
      { en: "I think you're in my seat.", fr: "Je crois que vous êtes à ma place." },
      { en: "Can I put my bag here?", fr: "Je peux mettre mon sac ici ?" },
      { en: "Excuse me, can I get by?", fr: "Pardon, je peux passer ?", note: "Pour sortir de ta rangée ou passer dans l'allée." },
      { en: "Chicken or pasta?", fr: "Poulet ou pâtes ?" },
      { en: "I'll have the chicken.", fr: "Je vais prendre le poulet." },
      { en: "Could I get some water?", fr: "Je pourrais avoir de l'eau ?" },
      { en: "Do you have a blanket?", fr: "Vous avez une couverture ?" },
      { en: "How long until we land?", fr: "Dans combien de temps on atterrit ?" },
    ],
    dialogue: {
      title: "Tu montes dans l'avion",
      turns: [
        { you: "Quelqu'un est assis à ta place : dis-le poliment.", answers: ["Excuse me, I think you're in my seat.", "Sorry, I think you're in my seat."] },
        { who: "Un passager", them: "Oh, sorry! My bad.", fr: "Oh, pardon ! Ma faute." },
        { them: "Hi there! Chicken or pasta?", fr: "Bonjour ! Poulet ou pâtes ?" },
        { you: "Prends le poulet, et demande de l'eau.", answers: ["I'll have the chicken. Could I get some water?"] },
        { them: "Sure, here you go.", fr: "Bien sûr, tenez." },
        { you: "Un peu plus tard : demande dans combien de temps on atterrit.", answers: ["How long until we land?"] },
        { them: "About an hour. Do you need anything else?", fr: "Environ une heure. Vous avez besoin d'autre chose ?" },
        { you: "Demande s'il a une couverture.", answers: ["Do you have a blanket?"] },
        { them: "Of course, I'll bring you one.", fr: "Bien sûr, je vous en apporte une." },
      ],
    },
  },
  {
    id: "lostbag",
    char: "grace",
    emoji: "🧳",
    title: "Bagage perdu",
    intro: "Si ta valise n'arrive pas, va au comptoir « Baggage services ». On te demandera de la décrire. En anglais, la taille vient avant la couleur : « a big black suitcase ».",
    phrases: [
      { en: "Where's baggage claim?", fr: "Où est le retrait des bagages ?" },
      { en: "My suitcase didn't arrive.", fr: "Ma valise n'est pas arrivée." },
      { en: "Here's my baggage tag.", fr: "Voici mon ticket de bagage." },
      { en: "It's a big black suitcase.", fr: "C'est une grande valise noire.", note: "La taille avant la couleur : « big black », jamais « black big »." },
      { en: "When will it get here?", fr: "Quand est-ce qu'elle va arriver ?" },
      { en: "Can you deliver it to my hotel?", fr: "Vous pouvez la livrer à mon hôtel ?" },
      { en: "I need it today.", fr: "J'en ai besoin aujourd'hui." },
      { en: "Who should I call?", fr: "Qui dois-je appeler ?" },
    ],
    dialogue: {
      title: "Ta valise n'est pas sur le tapis",
      turns: [
        { them: "Hi, how can I help?", fr: "Bonjour, je peux vous aider ?" },
        { you: "Dis que ta valise n'est pas arrivée.", answers: ["My suitcase didn't arrive.", "Hi, my suitcase didn't arrive."] },
        { them: "I'm sorry. Do you have your baggage tag?", fr: "Je suis désolée. Vous avez votre ticket de bagage ?" },
        { you: "Donne-le : voici ton ticket.", answers: ["Here's my baggage tag.", "Yes, here's my baggage tag."] },
        { them: "Thanks. What does it look like?", fr: "Merci. Elle ressemble à quoi ?" },
        { you: "Décris-la : une grande valise noire.", answers: ["It's a big black suitcase."] },
        { them: "Okay. It should arrive on the next flight.", fr: "D'accord. Elle devrait arriver par le prochain vol." },
        { you: "Demande s'ils peuvent la livrer à ton hôtel.", answers: ["Can you deliver it to my hotel?"] },
        { them: "Yes, no problem. We'll call you.", fr: "Oui, pas de problème. On vous appellera." },
      ],
    },
  },
  {
    id: "bank",
    char: "daniel",
    emoji: "🏦",
    title: "À la banque",
    intro: "À l'étranger, tu auras peut-être besoin de retirer de l'argent ou de régler un souci de carte. Un distributeur = « an ATM » aux États-Unis, « a cash machine » au Royaume-Uni.",
    phrases: [
      { en: "Where's the nearest ATM?", fr: "Où est le distributeur le plus proche ?" },
      { en: "My card isn't working.", fr: "Ma carte ne marche pas." },
      { en: "The machine ate my card.", fr: "Le distributeur a avalé ma carte.", note: "« Ate » = a mangé. Très courant !" },
      { en: "I need to block my card.", fr: "Je dois faire opposition sur ma carte." },
      { en: "Can I withdraw some cash?", fr: "Je peux retirer de l'argent liquide ?" },
      { en: "Is there a fee?", fr: "Il y a des frais ?" },
      { en: "Here's my ID.", fr: "Voici ma pièce d'identité.", note: "« ID » se prononce « aï-di »." },
      { en: "I'd like to open an account.", fr: "Je voudrais ouvrir un compte." },
    ],
    dialogue: {
      title: "Un souci de carte à la banque",
      turns: [
        { them: "Hi, how can I help you today?", fr: "Bonjour, que puis-je faire pour vous ?" },
        { you: "Dis que le distributeur a avalé ta carte.", answers: ["The machine ate my card.", "Hi, the machine ate my card."] },
        { them: "Oh no! Do you have some ID?", fr: "Oh non ! Vous avez une pièce d'identité ?" },
        { you: "Donne-la : voici ta pièce d'identité.", answers: ["Here's my ID.", "Sure, here's my ID."] },
        { them: "Thanks. Okay, we'll get your card back tomorrow.", fr: "Merci. Bon, on récupère votre carte demain." },
        { you: "Demande si tu peux retirer de l'argent liquide en attendant.", answers: ["Can I withdraw some cash?", "Can I withdraw some cash today?"] },
        { them: "Sure, at the counter.", fr: "Bien sûr, au guichet." },
        { you: "Demande s'il y a des frais.", answers: ["Is there a fee?"] },
        { them: "No, it's free. Have a nice day!", fr: "Non, c'est gratuit. Bonne journée !" },
      ],
    },
  },

  // ---------- Carrière ----------
  {
    id: "interview",
    char: "olivia",
    emoji: "🤝",
    title: "Entretien d'embauche",
    intro: "En entretien en anglais, on attend des réponses courtes et positives. « Tell me about yourself » est presque toujours la première question : prépare ta réponse !",
    phrases: [
      { en: "Thanks for having me.", fr: "Merci de me recevoir." },
      { en: "Tell me about yourself.", fr: "Parlez-moi de vous." },
      { en: "I have five years of experience.", fr: "J'ai cinq ans d'expérience." },
      { en: "I'm a fast learner.", fr: "J'apprends vite." },
      { en: "I work well in a team.", fr: "Je travaille bien en équipe." },
      { en: "Why do you want this job?", fr: "Pourquoi voulez-vous ce poste ?" },
      { en: "I'm looking for a new challenge.", fr: "Je cherche un nouveau défi." },
      { en: "Do you have any questions for us?", fr: "Vous avez des questions pour nous ?" },
    ],
    dialogue: {
      title: "Entretien en visio",
      turns: [
        { them: "Hi, thanks for joining us! How are you?", fr: "Bonjour, merci d'être là ! Comment allez-vous ?" },
        { you: "Dis que ça va bien, et merci de te recevoir.", answers: ["I'm good, thanks for having me.", "Great, thanks for having me.", "Pretty good, thanks for having me."] },
        { them: "So, tell me about yourself.", fr: "Alors, parlez-moi de vous." },
        { you: "Présente-toi en une ou deux phrases.", free: true, examples: ["I have five years of experience in marketing.", "I'm a fast learner and I work well in a team."] },
        { them: "Great. Why do you want this job?", fr: "Très bien. Pourquoi voulez-vous ce poste ?" },
        { you: "Dis que tu cherches un nouveau défi, et que tu apprends vite.", answers: ["I'm looking for a new challenge, and I'm a fast learner."] },
        { them: "Perfect. Do you have any questions for us?", fr: "Parfait. Vous avez des questions pour nous ?" },
        { you: "Pose une question, ou dis que non, merci.", free: true, examples: ["When can I start?", "What does a typical day look like?", "No, I'm good. Thank you!"] },
        { them: "Thanks so much. We'll be in touch!", fr: "Merci beaucoup. On vous recontacte !" },
      ],
    },
  },
  {
    id: "networking",
    char: "raj",
    emoji: "🏢",
    title: "Se présenter pro",
    intro: "Dans un contexte pro, on se présente avec son rôle et son entreprise. Et on finit souvent par « Let's keep in touch » (restons en contact).",
    phrases: [
      { en: "Hi, I don't think we've met.", fr: "Bonjour, je crois qu'on ne se connaît pas." },
      { en: "What company are you with?", fr: "Vous êtes dans quelle entreprise ?" },
      { en: "I'm in charge of sales.", fr: "Je suis responsable des ventes.", note: "Remplace par ton domaine : marketing, projects, customer service…" },
      { en: "What does your company do?", fr: "Que fait votre entreprise ?" },
      { en: "That sounds interesting.", fr: "Ça a l'air intéressant." },
      { en: "Here's my card.", fr: "Voici ma carte." },
      { en: "Let's keep in touch.", fr: "Restons en contact." },
      { en: "Are you on LinkedIn?", fr: "Vous êtes sur LinkedIn ?" },
    ],
    dialogue: {
      title: "Un salon professionnel",
      turns: [
        { you: "Va vers quelqu'un : dis bonjour, je crois qu'on ne se connaît pas.", answers: ["Hi, I don't think we've met."] },
        { them: "Hi! I'm Raj. Nice to meet you.", fr: "Bonjour ! Moi c'est Raj. Enchanté." },
        { you: "Dis enchanté(e), et demande dans quelle entreprise il est.", answers: ["Nice to meet you. What company are you with?"] },
        { them: "I'm with GreenTech. We make solar panels.", fr: "Je suis chez GreenTech. On fabrique des panneaux solaires." },
        { you: "Dis que ça a l'air intéressant.", answers: ["That sounds interesting!"] },
        { them: "Thanks! And what do you do?", fr: "Merci ! Et vous, vous faites quoi ?" },
        { you: "Présente ton rôle.", free: true, examples: ["I'm in charge of sales.", "I work in marketing.", "I'm a project manager."] },
        { them: "Cool. Are you on LinkedIn?", fr: "Cool. Vous êtes sur LinkedIn ?" },
        { you: "Réponds oui : restons en contact.", answers: ["Yes! Let's keep in touch.", "Yeah, let's keep in touch."] },
      ],
    },
  },
  {
    id: "client",
    char: "steve",
    emoji: "📧",
    title: "Avec un client",
    intro: "Avec un client, on reste poli mais direct. « I'll look into it » (je regarde ça) et « I'll keep you posted » (je vous tiens au courant) sont indispensables.",
    phrases: [
      { en: "Thanks for reaching out.", fr: "Merci de nous avoir contactés.", note: "Formule très courante au début d'un mail ou d'un appel." },
      { en: "How can I help you?", fr: "Comment puis-je vous aider ?" },
      { en: "I'm sorry for the trouble.", fr: "Désolé(e) pour le désagrément." },
      { en: "I'll look into it.", fr: "Je vais regarder ça." },
      { en: "I'll keep you posted.", fr: "Je vous tiens au courant." },
      { en: "Does that work for you?", fr: "Ça vous convient ?" },
      { en: "Let me double-check.", fr: "Laissez-moi vérifier.", note: "« Double-check » = revérifier, s'assurer." },
      { en: "Is there anything else I can do?", fr: "Je peux faire autre chose pour vous ?" },
    ],
    dialogue: {
      title: "Un client mécontent t'appelle",
      turns: [
        { them: "Hi, this is Steve from Brightline. Our order still hasn't arrived.", fr: "Bonjour, c'est Steve de Brightline. Notre commande n'est toujours pas arrivée." },
        { you: "Remercie-le de t'avoir contacté(e), et excuse-toi pour le désagrément.", answers: ["Thanks for reaching out. I'm sorry for the trouble."] },
        { them: "It was supposed to arrive on Monday.", fr: "Elle devait arriver lundi." },
        { you: "Dis que tu regardes ça et que tu le tiens au courant.", answers: ["I'll look into it and keep you posted.", "I'll look into it. I'll keep you posted."] },
        { them: "Thanks. Can you call me back this afternoon?", fr: "Merci. Vous pouvez me rappeler cet après-midi ?" },
        { you: "Propose 15 h, et demande si ça lui convient.", answers: ["How about three? Does that work for you?", "Let's say three? Does that work for you?"] },
        { them: "Perfect. Talk to you then!", fr: "Parfait. À tout à l'heure !" },
      ],
    },
  },
];
