// Situations ajoutées en phase 1 (chapitres 2 à 4). Même format que dans data.js.

export const MORE_CHARACTERS = {
  marcus: { name: "Marcus", role: "Chauffeur VTC", emoji: "🚕", color: "#F59E0B" },
  linda: { name: "Linda", role: "Ton hôte Airbnb", emoji: "🏠", color: "#0EA5E9" },
  priya: { name: "Priya", role: "Pharmacienne", emoji: "💊", color: "#10B981" },
  ross: { name: "Dr Ross", role: "Médecin", emoji: "🩺", color: "#64748B" },
  tom: { name: "Tom", role: "Ton voisin", emoji: "🌤️", color: "#EF4444" },
  nina: { name: "Nina", role: "Ta coloc", emoji: "🛋️", color: "#D946EF" },
  diane: { name: "Diane", role: "Ta cheffe", emoji: "📊", color: "#6366F1" },
  tony: { name: "Tony", role: "Livreur", emoji: "📦", color: "#A16207" },
};

export const MORE_SITUATIONS = [
  // ---------- Chapitre 2 : Sortir et bouger ----------
  {
    id: "transport",
    char: "marcus",
    emoji: "🚕",
    title: "En taxi, en Uber",
    intro: "En VTC, le chauffeur fait souvent un peu la conversation. Pour le métro, on dit « the subway » à New York et « the tube » à Londres.",
    phrases: [
      { en: "Are you my Uber?", fr: "C'est vous mon Uber ?", note: "Pour vérifier que c'est le bon chauffeur. Lui te demandera ton prénom." },
      { en: "Can you drop me off here?", fr: "Vous pouvez me déposer ici ?", note: "« Drop off » = déposer. L'inverse : « pick up » = venir chercher." },
      { en: "How long does it take?", fr: "Ça prend combien de temps ?" },
      { en: "Is this the right stop?", fr: "C'est le bon arrêt ?" },
      { en: "I missed my stop.", fr: "J'ai raté mon arrêt." },
      { en: "Which line goes downtown?", fr: "Quelle ligne va au centre-ville ?", note: "« Downtown » = le centre-ville, surtout aux États-Unis." },
      { en: "Traffic is crazy today.", fr: "Il y a un trafic de fou aujourd'hui." },
      { en: "Keep the change.", fr: "Gardez la monnaie." },
    ],
    dialogue: {
      title: "Un chauffeur VTC vient te chercher",
      turns: [
        { them: "Hey! Are you going to the airport?", fr: "Salut ! Tu vas à l'aéroport ?" },
        { you: "Réponds que oui, et demande combien de temps ça prend.", answers: ["Yes! How long does it take?", "Yeah, how long does it take?"] },
        { them: "About thirty minutes. Traffic is crazy today.", fr: "Environ trente minutes. Il y a un trafic de fou aujourd'hui." },
        { you: "Dis que ce n'est pas grave : pas de souci.", answers: ["No worries.", "Oh, no worries."] },
        { them: "So, where are you from?", fr: "Alors, tu viens d'où ?" },
        { you: "Dis que tu viens de France.", answers: ["I'm from France."] },
        { them: "Nice! … Almost there. Where do you want me to stop?", fr: "Sympa ! … On y est presque. Tu veux que je m'arrête où ?" },
        { you: "Demande-lui de te déposer ici.", answers: ["Can you drop me off here?", "You can drop me off here.", "Can you drop me off here, please?"] },
        { them: "Sure thing. Have a good flight!", fr: "Pas de problème. Bon vol !" },
      ],
    },
  },
  {
    id: "hotel",
    char: "linda",
    emoji: "🏨",
    title: "À l'hôtel, en Airbnb",
    intro: "À l'arrivée, on dit simplement « I have a reservation » ou « I'm checking in ». En Airbnb, l'hôte te donne souvent toutes les infos par message.",
    phrases: [
      { en: "Hi, I have a reservation.", fr: "Bonjour, j'ai une réservation." },
      { en: "I'm checking in.", fr: "Je viens faire le check-in.", note: "Pour partir : « I'm checking out »." },
      { en: "What's the Wi-Fi password?", fr: "C'est quoi le mot de passe du wifi ?", note: "« Wi-Fi » se prononce « waï-faï »." },
      { en: "What time is checkout?", fr: "À quelle heure faut-il libérer la chambre ?" },
      { en: "Can I leave my bags here?", fr: "Je peux laisser mes bagages ici ?" },
      { en: "The shower isn't working.", fr: "La douche ne marche pas." },
      { en: "Could I get an extra towel?", fr: "Je pourrais avoir une serviette en plus ?" },
      { en: "Is breakfast included?", fr: "Le petit-déj est compris ?" },
    ],
    dialogue: {
      title: "Tu arrives chez ton hôte Airbnb",
      turns: [
        { them: "Hi! You must be my guest. Welcome!", fr: "Salut ! C'est toi qui as réservé, je suppose. Bienvenue !" },
        { you: "Dis bonjour, et que tu viens faire le check-in.", answers: ["Hi! I'm checking in.", "Hi, I'm checking in."] },
        { them: "Perfect. Here are the keys. Any questions?", fr: "Parfait. Voilà les clés. Des questions ?" },
        { you: "Demande le mot de passe du wifi.", answers: ["What's the Wi-Fi password?"] },
        { them: "It's on the fridge. Anything else?", fr: "C'est sur le frigo. Autre chose ?" },
        { you: "Demande à quelle heure il faut libérer l'appart (le checkout).", answers: ["What time is checkout?"] },
        { them: "Eleven a.m. Enjoy your stay!", fr: "11 h. Bon séjour !" },
      ],
    },
  },
  {
    id: "bar",
    char: "chloe",
    emoji: "🍹",
    title: "Soirée au bar",
    intro: "Au bar, on commande au comptoir et on paie tout de suite, ou on ouvre une « tab » (une ardoise). Avec la musique, attends-toi à devoir faire répéter !",
    phrases: [
      { en: "What are you drinking?", fr: "Tu bois quoi ?", note: "Souvent pour proposer de t'offrir un verre." },
      { en: "I'll have a beer.", fr: "Je vais prendre une bière." },
      { en: "This one's on me.", fr: "Celui-là, c'est pour moi." },
      { en: "Can I open a tab?", fr: "Je peux ouvrir une ardoise ?", note: "« A tab » = une note qu'on paie à la fin de la soirée." },
      { en: "It's so loud in here!", fr: "Il y a trop de bruit ici !" },
      { en: "Do you come here often?", fr: "Tu viens souvent ici ?", note: "Phrase de drague cliché… mais aussi une vraie question !" },
      { en: "I love this song!", fr: "J'adore cette chanson !" },
      { en: "I should get going.", fr: "Je devrais y aller.", note: "Pour partir poliment en fin de soirée." },
    ],
    dialogue: {
      title: "Tu retrouves Chloe dans un bar",
      turns: [
        { them: "Hey, you made it! What are you drinking?", fr: "Hé, t'as pu venir ! Tu bois quoi ?" },
        { you: "Dis que tu vas prendre une bière.", answers: ["I'll have a beer.", "I'll have a beer, thanks."] },
        { them: "Cool. This one's on me!", fr: "Cool. Celle-là, c'est pour moi !" },
        { you: "Remercie-la beaucoup.", answers: ["Thanks a lot!", "Thank you so much!"] },
        { them: "Oh, I love this song! Do you come here often?", fr: "Oh, j'adore cette chanson ! Tu viens souvent ici ?" },
        { you: "Dis : pardon, quoi ? Il y a trop de bruit ici !", answers: ["Sorry, what? It's so loud in here!"] },
        { them: "Haha, yeah! … It's getting late.", fr: "Haha, ouais ! … Il se fait tard." },
        { you: "Dis que tu devrais y aller.", answers: ["I should get going.", "Yeah, I should get going."] },
        { them: "Okay! Catch you later!", fr: "OK ! À plus !" },
      ],
    },
  },
  {
    id: "pharmacy",
    char: "priya",
    emoji: "💊",
    title: "À la pharmacie",
    intro: "Aux États-Unis, beaucoup de médicaments sont en libre-service (« over the counter »). Explique simplement ce que tu as : « I have a… ».",
    phrases: [
      { en: "I'm not feeling well.", fr: "Je ne me sens pas bien." },
      { en: "I have a headache.", fr: "J'ai mal à la tête." },
      { en: "I have a sore throat.", fr: "J'ai mal à la gorge." },
      { en: "I think I have a cold.", fr: "Je crois que j'ai un rhume." },
      { en: "Do you have something for a cough?", fr: "Vous avez quelque chose contre la toux ?" },
      { en: "How many times a day?", fr: "Combien de fois par jour ?" },
      { en: "Do I need a prescription?", fr: "J'ai besoin d'une ordonnance ?" },
      { en: "Are you allergic to anything?", fr: "Vous êtes allergique à quelque chose ?" },
    ],
    dialogue: {
      title: "Tu ne te sens pas bien, tu vas à la pharmacie",
      turns: [
        { them: "Hi there, how can I help?", fr: "Bonjour, je peux vous aider ?" },
        { you: "Dis que tu ne te sens pas bien, tu crois que tu as un rhume.", answers: ["I'm not feeling well. I think I have a cold."] },
        { them: "Oh, sorry to hear that. Any other symptoms?", fr: "Oh, désolée. D'autres symptômes ?" },
        { you: "Dis que tu as mal à la gorge.", answers: ["I have a sore throat.", "I have a sore throat too."] },
        { them: "Okay, these should help. Are you allergic to anything?", fr: "D'accord, ça devrait aider. Vous êtes allergique à quelque chose ?" },
        { you: "Réponds non, et demande combien de fois par jour il faut les prendre.", answers: ["No. How many times a day?", "Nope, how many times a day?"] },
        { them: "Twice a day, after meals. Feel better!", fr: "Deux fois par jour, après les repas. Bon rétablissement !" },
      ],
    },
  },
  {
    id: "doctor",
    char: "ross",
    emoji: "🩺",
    title: "Chez le médecin",
    intro: "Le médecin te demandera « What brings you in today? » (qu'est-ce qui vous amène ?). Pour dire depuis quand : « for two days », « since Monday ».",
    phrases: [
      { en: "I'd like to make an appointment.", fr: "Je voudrais prendre rendez-vous.", note: "Ici « I'd like » est normal : c'est une demande un peu formelle." },
      { en: "My stomach hurts.", fr: "J'ai mal au ventre." },
      { en: "It hurts here.", fr: "J'ai mal ici.", note: "En montrant l'endroit." },
      { en: "I've had a fever since yesterday.", fr: "J'ai de la fièvre depuis hier." },
      { en: "For two days.", fr: "Depuis deux jours." },
      { en: "I feel dizzy.", fr: "J'ai la tête qui tourne." },
      { en: "Is it serious?", fr: "C'est grave ?" },
      { en: "I'm allergic to penicillin.", fr: "Je suis allergique à la pénicilline." },
    ],
    dialogue: {
      title: "Consultation chez le médecin",
      turns: [
        { them: "Hi, I'm Dr. Ross. What brings you in today?", fr: "Bonjour, je suis le Dr Ross. Qu'est-ce qui vous amène ?" },
        { you: "Dis que tu as mal au ventre.", answers: ["My stomach hurts.", "My stomach hurts a lot."] },
        { them: "I see. How long has it been hurting?", fr: "Je vois. Depuis combien de temps ?" },
        { you: "Réponds : depuis deux jours.", answers: ["For two days.", "For two days now."] },
        { them: "Any fever?", fr: "De la fièvre ?" },
        { you: "Dis que tu as de la fièvre depuis hier.", answers: ["I've had a fever since yesterday.", "Yes, I've had a fever since yesterday."] },
        { them: "Okay, let me take a look.", fr: "D'accord, je vais vous examiner." },
        { you: "Demande si c'est grave.", answers: ["Is it serious?"] },
        { them: "Don't worry, it's just a bug. Get some rest and drink lots of water.", fr: "Ne vous inquiétez pas, c'est juste un petit virus. Reposez-vous et buvez beaucoup d'eau." },
      ],
    },
  },
  {
    id: "phone",
    char: "linda",
    emoji: "📞",
    title: "Au téléphone",
    intro: "Au téléphone, c'est plus dur : pas de gestes, pas de lèvres à lire. N'hésite pas à faire répéter ou épeler (« Could you spell that? »).",
    phrases: [
      { en: "Can you hear me?", fr: "Tu m'entends ?" },
      { en: "You're breaking up.", fr: "Ça coupe.", note: "Quand la connexion est mauvaise." },
      { en: "Sorry, I missed your call.", fr: "Désolé(e), j'ai raté ton appel." },
      { en: "Can I call you back?", fr: "Je peux te rappeler ?" },
      { en: "Could you spell that?", fr: "Vous pouvez épeler ?" },
      { en: "Hold on a second.", fr: "Attends une seconde.", note: "On dit aussi « Hang on »." },
      { en: "I'm calling about the apartment.", fr: "J'appelle au sujet de l'appartement." },
      { en: "Talk to you later!", fr: "On se reparle plus tard !", note: "Pour raccrocher entre amis. Par texto : « TTYL »." },
    ],
    dialogue: {
      title: "Tu appelles ton hôte : il y a un problème",
      turns: [
        { you: "Dis : salut, j'appelle au sujet de l'appartement.", answers: ["Hi, I'm calling about the apartment."] },
        { them: "Oh hi! Sorry, you're breaking up a little.", fr: "Oh salut ! Désolée, ça coupe un peu." },
        { you: "Demande si elle t'entend maintenant.", answers: ["Can you hear me now?", "Can you hear me?"] },
        { them: "Yes, much better! What's going on?", fr: "Oui, beaucoup mieux ! Qu'est-ce qui se passe ?" },
        { you: "Dis que la douche ne marche pas.", answers: ["The shower isn't working."] },
        { them: "Oh no! Hold on a second… Can I call you back in five minutes?", fr: "Oh non ! Attends une seconde… Je peux te rappeler dans cinq minutes ?" },
        { you: "Accepte : ça marche, on se reparle plus tard.", answers: ["Sounds good. Talk to you later!", "Sure, talk to you later!"] },
      ],
    },
  },

  // ---------- Chapitre 3 : Discuter ----------
  {
    id: "weekend",
    char: "sam",
    emoji: "🛋️",
    title: "Ton week-end",
    intro: "Le lundi, tout le monde demande « How was your weekend? ». Une réponse courte et une question en retour suffisent, pas besoin de détails.",
    phrases: [
      { en: "How was your weekend?", fr: "C'était comment ton week-end ?" },
      { en: "It was pretty chill.", fr: "C'était plutôt tranquille.", note: "« Chill » = détendu, cool. Très courant." },
      { en: "I didn't do much.", fr: "Je n'ai pas fait grand-chose." },
      { en: "I just stayed home.", fr: "Je suis juste resté(e) à la maison." },
      { en: "I went out with some friends.", fr: "Je suis sorti(e) avec des amis." },
      { en: "Any plans for the weekend?", fr: "Des projets pour le week-end ?" },
      { en: "Not really.", fr: "Pas vraiment." },
      { en: "Sounds fun!", fr: "Ça a l'air sympa !" },
    ],
    dialogue: {
      title: "Lundi matin, Sam t'écrit",
      turns: [
        { them: "Hey! How was your weekend?", fr: "Salut ! C'était comment ton week-end ?" },
        { you: "Dis que c'était plutôt tranquille, tu n'as pas fait grand-chose.", answers: ["It was pretty chill. I didn't do much.", "Pretty chill. I didn't do much."] },
        { them: "Same here. I just stayed home and watched Netflix.", fr: "Pareil. Je suis juste resté à la maison devant Netflix." },
        { you: "Réagis gentiment : ça a l'air sympa !", answers: ["Sounds fun!"] },
        { them: "Haha, it was. Any plans for next weekend?", fr: "Haha, c'était cool. Des projets pour le week-end prochain ?" },
        { you: "Réponds : pas vraiment. Puis propose d'aller boire un verre.", answers: ["Not really. Wanna grab a drink?", "Not really, do you want to grab a drink?"] },
        { them: "I'm down!", fr: "Partant !" },
      ],
    },
  },
  {
    id: "weather",
    char: "tom",
    emoji: "🌦️",
    title: "La météo",
    intro: "La météo, c'est LE sujet pour briser la glace, surtout au Royaume-Uni. Attention : aux États-Unis, la température est en degrés Fahrenheit.",
    phrases: [
      { en: "Nice day, huh?", fr: "Belle journée, hein ?" },
      { en: "It's freezing!", fr: "Il fait un froid de canard !" },
      { en: "It's so hot today.", fr: "Il fait trop chaud aujourd'hui." },
      { en: "It looks like rain.", fr: "On dirait qu'il va pleuvoir." },
      { en: "It's pouring.", fr: "Il pleut des cordes." },
      { en: "I can't wait for summer.", fr: "J'ai hâte d'être en été." },
      { en: "Tell me about it.", fr: "M'en parle pas.", note: "Pour dire « je suis bien d'accord », pas « raconte-moi »." },
      { en: "Have a good one!", fr: "Bonne journée !", note: "Version décontractée de « Have a nice day »." },
    ],
    dialogue: {
      title: "Tu croises ton voisin devant l'immeuble",
      turns: [
        { them: "Morning! It's freezing today, huh?", fr: "Bonjour ! Il fait un froid de canard aujourd'hui, hein ?" },
        { you: "Dis que oui, et que tu as hâte d'être en été.", answers: ["Yeah! I can't wait for summer.", "Yes, I can't wait for summer."] },
        { them: "Same here. And it looks like rain, too.", fr: "Pareil. Et on dirait qu'il va pleuvoir, en plus." },
        { you: "Réponds : m'en parle pas.", answers: ["Tell me about it.", "Ugh, tell me about it."] },
        { them: "Well, have a good one!", fr: "Bon, bonne journée !" },
        { you: "Souhaite-lui bonne journée aussi.", answers: ["You too!", "Have a good one!", "Thanks, you too!"] },
      ],
    },
  },
  {
    id: "hobbies",
    char: "chloe",
    emoji: "🎸",
    title: "Tes goûts et loisirs",
    intro: "Pour parler de ce que tu aimes, « I'm into… » (je suis à fond dans…) est très courant. « What do you do for fun? » = qu'est-ce que tu fais de ton temps libre ?",
    phrases: [
      { en: "What do you do for fun?", fr: "Tu fais quoi pour t'amuser ?" },
      { en: "I'm really into music.", fr: "Je suis à fond dans la musique." },
      { en: "I love watching movies.", fr: "J'adore regarder des films." },
      { en: "I play soccer on weekends.", fr: "Je joue au foot le week-end.", note: "Aux États-Unis, le foot = « soccer » (« football » = foot américain). Au Royaume-Uni, c'est « football »." },
      { en: "I'm not really into sports.", fr: "Je ne suis pas trop sport." },
      { en: "Have you seen it?", fr: "Tu l'as vu ?" },
      { en: "Me too!", fr: "Moi aussi !" },
      { en: "Me neither.", fr: "Moi non plus." },
    ],
    dialogue: {
      title: "Chloe t'écrit pour mieux te connaître",
      turns: [
        { them: "So, what do you do for fun?", fr: "Alors, tu fais quoi pour t'amuser ?" },
        { you: "Dis que tu es à fond dans la musique, et que tu adores regarder des films.", answers: ["I'm really into music, and I love watching movies.", "I'm really into music. I love watching movies."] },
        { them: "Me too! Have you seen the new Spider-Man?", fr: "Moi aussi ! T'as vu le nouveau Spider-Man ?" },
        { you: "Réponds librement : oui ou non.", free: true, examples: ["Yeah, I loved it!", "Not yet.", "No, is it good?"] },
        { them: "I'm not really into sports, but my brother plays soccer every weekend.", fr: "Je ne suis pas trop sport, mais mon frère joue au foot tous les week-ends." },
        { you: "Dis : moi non plus, je ne suis pas trop sport.", answers: ["Me neither. I'm not really into sports."] },
        { them: "Haha, we have a lot in common!", fr: "Haha, on a plein de points communs !" },
      ],
    },
  },
  {
    id: "opinions",
    char: "nina",
    emoji: "🍿",
    title: "Donner son avis",
    intro: "Pour donner ton avis : « I think… », « To be honest… » (pour être honnête). Pour être d'accord avec enthousiasme : « Totally! » ou « I know, right? ».",
    phrases: [
      { en: "What do you think?", fr: "T'en penses quoi ?" },
      { en: "I think it's great.", fr: "Je trouve ça génial." },
      { en: "To be honest, it was boring.", fr: "Pour être honnête, c'était ennuyeux." },
      { en: "Totally!", fr: "Carrément !" },
      { en: "I know, right?", fr: "Grave ! / C'est clair !", note: "Pour être d'accord avec enthousiasme." },
      { en: "I'm not sure.", fr: "Je ne suis pas sûr(e)." },
      { en: "It's up to you.", fr: "C'est toi qui vois." },
      { en: "I don't mind.", fr: "Ça m'est égal.", note: "Gentil : « ça me va, choisis »." },
    ],
    dialogue: {
      title: "Ta coloc veut regarder un film",
      turns: [
        { them: "Wanna watch a movie tonight? What do you think?", fr: "On regarde un film ce soir ? T'en penses quoi ?" },
        { you: "Accepte : ça marche !", answers: ["Sounds good!", "Yeah, sounds good!", "I think it's great!"] },
        { them: "Cool! Horror or comedy?", fr: "Cool ! Horreur ou comédie ?" },
        { you: "Dis que ça t'est égal, c'est elle qui voit.", answers: ["I don't mind. It's up to you."] },
        { them: "So? What did you think?", fr: "(Après le film) Alors ? T'en as pensé quoi ?" },
        { you: "Dis que pour être honnête, c'était ennuyeux.", answers: ["To be honest, it was boring.", "Honestly, it was boring."] },
        { them: "I know, right? Never again!", fr: "Grave ! Plus jamais !" },
      ],
    },
  },
  {
    id: "anecdote",
    char: "sam",
    emoji: "😱",
    title: "Raconter une histoire",
    intro: "Pour raconter un truc, on commence par « Guess what? » ou « You won't believe this ». Et ceux qui écoutent réagissent beaucoup : « No way! », « What happened? ».",
    phrases: [
      { en: "You won't believe this.", fr: "Tu ne vas pas le croire." },
      { en: "Guess what happened?", fr: "Devine ce qui s'est passé ?" },
      { en: "What happened?", fr: "Qu'est-ce qui s'est passé ?" },
      { en: "I lost my phone.", fr: "J'ai perdu mon téléphone." },
      { en: "It was so embarrassing.", fr: "C'était trop la honte." },
      { en: "And then what?", fr: "Et après ?" },
      { en: "That's hilarious!", fr: "C'est hilarant !" },
      { en: "Long story short, I found it.", fr: "Bref, je l'ai retrouvé.", note: "« Long story short » = pour faire court." },
    ],
    dialogue: {
      title: "Sam a une histoire à raconter",
      turns: [
        { them: "Dude, you won't believe this.", fr: "Mec, tu ne vas pas le croire. (dude = mec)" },
        { you: "Demande ce qui s'est passé.", answers: ["What happened?"] },
        { them: "I lost my phone on the bus yesterday!", fr: "J'ai perdu mon téléphone dans le bus hier !" },
        { you: "Réagis : pas possible ! Et après ?", answers: ["No way! And then what?"] },
        { them: "I called it, and the bus driver answered! It was so embarrassing.", fr: "Je l'ai appelé, et c'est le chauffeur du bus qui a répondu ! C'était trop la honte." },
        { you: "Dis que c'est hilarant !", answers: ["That's hilarious!", "Haha, that's hilarious!"] },
        { them: "Long story short, I got it back. Phew!", fr: "Bref, je l'ai récupéré. Ouf !" },
      ],
    },
  },
  {
    id: "feelings",
    char: "nina",
    emoji: "😮‍💨",
    title: "Comment tu te sens",
    intro: "On décrit son état avec des expressions imagées : « I'm beat » (je suis crevé(e)), « I'm starving » (je meurs de faim). Bien plus naturel que « I'm tired » ou « I'm hungry ».",
    phrases: [
      { en: "I'm beat.", fr: "Je suis crevé(e)." },
      { en: "I'm starving!", fr: "Je meurs de faim !", note: "Pour une petite faim : « I'm a bit hungry »." },
      { en: "I'm so bored.", fr: "Je m'ennuie trop." },
      { en: "I'm stressed out.", fr: "Je suis stressé(e)." },
      { en: "I'm in a good mood today.", fr: "Je suis de bonne humeur aujourd'hui." },
      { en: "What's wrong?", fr: "Qu'est-ce qui ne va pas ?" },
      { en: "I'm fine, just tired.", fr: "Ça va, je suis juste fatigué(e)." },
      { en: "Let's order pizza.", fr: "On commande une pizza." },
    ],
    dialogue: {
      title: "Tu rentres à la maison, ta coloc est là",
      turns: [
        { them: "Hey! You look tired. What's wrong?", fr: "Salut ! T'as l'air fatigué(e). Qu'est-ce qui ne va pas ?" },
        { you: "Dis que ça va, tu es juste fatigué(e). Tu es crevé(e).", answers: ["I'm fine, just tired. I'm beat.", "I'm fine, just tired."] },
        { them: "Long day, huh? Are you hungry?", fr: "Longue journée, hein ? T'as faim ?" },
        { you: "Dis que tu meurs de faim !", answers: ["I'm starving!", "Yeah, I'm starving!"] },
        { them: "Me too. What should we eat?", fr: "Moi aussi. On mange quoi ?" },
        { you: "Propose de commander une pizza.", answers: ["Let's order pizza."] },
        { them: "Best idea ever!", fr: "Meilleure idée de tous les temps !" },
      ],
    },
  },
  {
    id: "compliments",
    char: "chloe",
    emoji: "😊",
    title: "Faire un compliment",
    intro: "Les anglophones font facilement des compliments, même à des inconnus : « I love your shoes! ». Pour répondre, un simple « Thanks! » suffit, pas besoin de te justifier.",
    phrases: [
      { en: "I love your jacket!", fr: "J'adore ta veste !" },
      { en: "You look great!", fr: "Tu es superbe !" },
      { en: "That's really nice of you.", fr: "C'est vraiment gentil de ta part." },
      { en: "Where did you get it?", fr: "Tu l'as eu où ?" },
      { en: "It suits you.", fr: "Ça te va bien." },
      { en: "You're so good at this!", fr: "T'es trop doué(e) !" },
      { en: "Thanks, that means a lot.", fr: "Merci, ça me touche." },
      { en: "Oh, stop it!", fr: "Oh, arrête !", note: "Pour recevoir un compliment avec humour." },
    ],
    dialogue: {
      title: "Tu retrouves Chloe pour un café",
      turns: [
        { them: "Hey! Oh, I love your jacket!", fr: "Salut ! Oh, j'adore ta veste !" },
        { you: "Remercie-la : c'est vraiment gentil.", answers: ["Thanks, that's really nice of you."] },
        { them: "Where did you get it?", fr: "Tu l'as eue où ?" },
        { you: "Réponds librement.", free: true, examples: ["In Paris.", "Online.", "I don't remember!"] },
        { them: "Well, it suits you.", fr: "En tout cas, elle te va bien." },
        { you: "Retourne le compliment : tu es superbe aussi !", answers: ["You look great too!", "Thanks! You look great too!"] },
        { them: "Oh, stop it!", fr: "Oh, arrête !" },
      ],
    },
  },
  {
    id: "jobtalk",
    char: "tom",
    emoji: "👔",
    title: "Parler de ton boulot",
    intro: "Pour décrire ton travail : « I work in… » (un secteur), « I work for… » (une entreprise), « I'm a… » (un métier).",
    phrases: [
      { en: "I work in marketing.", fr: "Je travaille dans le marketing.", note: "Remplace par ton secteur : sales, IT, healthcare, retail…" },
      { en: "I work from home.", fr: "Je travaille de chez moi." },
      { en: "How do you like it?", fr: "Ça te plaît ?" },
      { en: "I love it.", fr: "J'adore." },
      { en: "It's a lot of work.", fr: "C'est beaucoup de boulot." },
      { en: "I'm looking for a new job.", fr: "Je cherche un nouveau boulot." },
      { en: "How long have you been doing that?", fr: "Tu fais ça depuis combien de temps ?" },
      { en: "About three years.", fr: "Environ trois ans." },
    ],
    dialogue: {
      title: "Ton voisin t'invite à prendre un café",
      turns: [
        { them: "So, what do you do?", fr: "Alors, tu fais quoi dans la vie ?" },
        { you: "Réponds avec ton métier ou ton secteur.", free: true, examples: ["I work in marketing.", "I'm a nurse.", "I work in IT."] },
        { them: "Oh, cool! How do you like it?", fr: "Oh, cool ! Ça te plaît ?" },
        { you: "Dis que tu adores, mais que c'est beaucoup de boulot.", answers: ["I love it, but it's a lot of work."] },
        { them: "How long have you been doing that?", fr: "Tu fais ça depuis combien de temps ?" },
        { you: "Réponds : environ trois ans.", answers: ["About three years."] },
        { them: "Nice. I work from home, so I'm here all day. Come by anytime!", fr: "Sympa. Moi je bosse de chez moi, donc je suis là toute la journée. Passe quand tu veux !" },
      ],
    },
  },

  // ---------- Chapitre 4 : Boulot et maison ----------
  {
    id: "videocall",
    char: "diane",
    emoji: "💻",
    title: "En visio",
    intro: "En visio, quelques phrases reviennent tout le temps : « You're on mute » (ton micro est coupé), « Can you see my screen? »… À connaître par cœur !",
    phrases: [
      { en: "Can you hear me okay?", fr: "Vous m'entendez bien ?" },
      { en: "You're on mute.", fr: "Ton micro est coupé." },
      { en: "Can you see my screen?", fr: "Vous voyez mon écran ?" },
      { en: "Sorry, I was on mute.", fr: "Pardon, mon micro était coupé." },
      { en: "Let's get started.", fr: "On commence." },
      { en: "Sorry, go ahead.", fr: "Pardon, vas-y.", note: "Quand deux personnes parlent en même temps." },
      { en: "Could you repeat the last part?", fr: "Tu pourrais répéter la dernière partie ?" },
      { en: "I have to jump off.", fr: "Je dois quitter l'appel.", note: "« Jump off » ou « hop off » = quitter une réunion en ligne." },
    ],
    dialogue: {
      title: "Réunion en visio avec ta cheffe",
      turns: [
        { them: "Hi everyone! Can you hear me okay?", fr: "Bonjour à tous ! Vous m'entendez bien ?" },
        { you: "Réponds : oui, je t'entends.", answers: ["Yes, I can hear you.", "Yeah, I can hear you fine."] },
        { them: "Great. Let's get started. So, about the project…", fr: "Super. On commence. Alors, pour le projet…" },
        { you: "Tu as parlé mais personne ne t'a entendu : dis « pardon, mon micro était coupé ».", answers: ["Sorry, I was on mute."] },
        { them: "No problem! Can you see my screen? We need to update the slides, check the numbers, and send everything to the client.", fr: "Pas de souci ! Tu vois mon écran ? Il faut mettre à jour les slides, vérifier les chiffres, et tout envoyer au client." },
        { you: "Réponds oui, et demande de répéter la dernière partie.", answers: ["Yes. Could you repeat the last part?"] },
        { them: "Sure. Send everything to the client by Friday.", fr: "Bien sûr. Tout envoyer au client d'ici vendredi." },
        { you: "Dis que tu dois quitter l'appel, désolé(e).", answers: ["Sorry, I have to jump off.", "I have to jump off, sorry."] },
        { them: "No worries, talk soon!", fr: "Pas de souci, à bientôt !" },
      ],
    },
  },
  {
    id: "swamped",
    char: "diane",
    emoji: "😵",
    title: "Débordé au boulot",
    intro: "Quand on est débordé : « I'm swamped » (je suis sous l'eau). Pour demander du temps, reste simple et positif : « Could I have until Friday? ».",
    phrases: [
      { en: "I'm swamped right now.", fr: "Je suis sous l'eau en ce moment." },
      { en: "Could I have until Friday?", fr: "Je pourrais avoir jusqu'à vendredi ?" },
      { en: "I'm almost done.", fr: "J'ai presque fini." },
      { en: "It'll be ready by tomorrow.", fr: "Ce sera prêt pour demain." },
      { en: "Sorry for the delay.", fr: "Désolé(e) pour le retard." },
      { en: "Can it wait?", fr: "Ça peut attendre ?" },
      { en: "That's my top priority.", fr: "C'est ma priorité numéro un." },
      { en: "Thanks for understanding.", fr: "Merci de ta compréhension." },
    ],
    dialogue: {
      title: "Ta cheffe passe te voir",
      turns: [
        { them: "Hey, how's the report going?", fr: "Salut, ça avance le rapport ?" },
        { you: "Dis que tu as presque fini, mais que tu es sous l'eau en ce moment.", answers: ["I'm almost done, but I'm swamped right now."] },
        { them: "I see. Can you send it today?", fr: "Je vois. Tu peux l'envoyer aujourd'hui ?" },
        { you: "Demande si tu pourrais avoir jusqu'à vendredi.", answers: ["Could I have until Friday?"] },
        { them: "Hmm, okay. But it's important.", fr: "Hmm, d'accord. Mais c'est important." },
        { you: "Rassure-la : c'est ta priorité numéro un. Et remercie-la de sa compréhension.", answers: ["That's my top priority. Thanks for understanding.", "It's my top priority. Thanks for understanding."] },
        { them: "No problem. Good luck!", fr: "Pas de problème. Bon courage !" },
      ],
    },
  },
  {
    id: "lunch",
    char: "jake",
    emoji: "🥪",
    title: "La pause déj",
    intro: "Entre collègues, on dit « grab lunch » (manger un bout). « What are you in the mood for? » = t'as envie de quoi ?",
    phrases: [
      { en: "Wanna grab lunch?", fr: "On va manger un bout ?" },
      { en: "What are you in the mood for?", fr: "T'as envie de quoi ?" },
      { en: "I could go for a burger.", fr: "Je mangerais bien un burger.", note: "« I could go for… » = j'ai bien envie de…" },
      { en: "There's a new place down the street.", fr: "Il y a un nouveau resto en bas de la rue." },
      { en: "I'm in!", fr: "Je suis partant(e) !", note: "Comme « I'm down »." },
      { en: "Give me five minutes.", fr: "Laisse-moi cinq minutes." },
      { en: "Let's split the bill.", fr: "On partage l'addition." },
      { en: "I'm so full.", fr: "J'ai trop mangé, je n'en peux plus." },
    ],
    dialogue: {
      title: "Midi au bureau",
      turns: [
        { them: "Hey, wanna grab lunch?", fr: "Hé, on va manger un bout ?" },
        { you: "Dis que tu es partant, mais demande cinq minutes.", answers: ["I'm in! Give me five minutes."] },
        { them: "Sure. What are you in the mood for?", fr: "OK. T'as envie de quoi ?" },
        { you: "Dis que tu mangerais bien un burger.", answers: ["I could go for a burger."] },
        { them: "Perfect, there's a new place down the street.", fr: "Parfait, il y a un nouveau resto en bas de la rue." },
        { them: "Ugh, I'm so full.", fr: "(Après le repas) Pfff, j'ai trop mangé." },
        { you: "Dis : moi aussi. Puis propose de partager l'addition.", answers: ["Me too. Let's split the bill.", "Same here. Let's split the bill."] },
        { them: "Sounds good!", fr: "Ça marche !" },
      ],
    },
  },
  {
    id: "delivery",
    char: "tony",
    emoji: "📦",
    title: "Livraisons et colis",
    intro: "Le livreur peut te demander de signer ou de confirmer ton nom. Un colis = « a package » aux États-Unis, « a parcel » au Royaume-Uni.",
    phrases: [
      { en: "I'll be there in a minute!", fr: "J'arrive dans une minute !" },
      { en: "Is this for you?", fr: "C'est pour vous ?" },
      { en: "Can you leave it at the door?", fr: "Vous pouvez le laisser devant la porte ?" },
      { en: "Where do I sign?", fr: "Je signe où ?" },
      { en: "I think this is the wrong address.", fr: "Je crois que ce n'est pas la bonne adresse." },
      { en: "My order hasn't arrived yet.", fr: "Ma commande n'est pas encore arrivée." },
      { en: "I'm here to pick up a package.", fr: "Je viens chercher un colis." },
      { en: "Thanks, have a nice day!", fr: "Merci, bonne journée !" },
    ],
    dialogue: {
      title: "On sonne chez toi",
      turns: [
        { them: "Hi! Delivery! I have a package.", fr: "Bonjour ! Livraison ! J'ai un colis." },
        { you: "Crie que tu arrives dans une minute !", answers: ["I'll be there in a minute!", "Coming! I'll be there in a minute!"] },
        { them: "Is this for you? Apartment 3B?", fr: "C'est pour vous ? Appartement 3B ?" },
        { you: "Dis que tu crois que ce n'est pas la bonne adresse.", answers: ["I think this is the wrong address.", "Sorry, I think this is the wrong address."] },
        { them: "Oh, my bad! … And this one?", fr: "Oups, ma faute ! … Et celui-là ?" },
        { you: "Celui-là est pour toi : demande où tu signes.", answers: ["Where do I sign?", "Yes! Where do I sign?"] },
        { them: "Right here. Have a good one!", fr: "Juste ici. Bonne journée !" },
        { you: "Remercie et souhaite-lui une bonne journée.", answers: ["Thanks, have a nice day!", "Thanks, you too!"] },
      ],
    },
  },
  {
    id: "chores",
    char: "nina",
    emoji: "🧽",
    title: "La vie en coloc",
    intro: "En colocation, il faut savoir négocier les tâches ménagères ! « Whose turn is it? » (c'est à qui ?) est indispensable.",
    phrases: [
      { en: "Whose turn is it to do the dishes?", fr: "C'est à qui de faire la vaisselle ?" },
      { en: "It's your turn.", fr: "C'est ton tour." },
      { en: "I'll take out the trash.", fr: "Je sors les poubelles." },
      { en: "Can you keep it down?", fr: "Tu peux faire moins de bruit ?", note: "Poli mais direct, pour une musique trop forte par exemple." },
      { en: "We're out of milk.", fr: "Il n'y a plus de lait." },
      { en: "I'll pick some up.", fr: "J'en rachète." },
      { en: "Do you mind if I invite some friends?", fr: "Ça te dérange si j'invite des amis ?" },
      { en: "Not at all!", fr: "Pas du tout !" },
    ],
    dialogue: {
      title: "Dans la cuisine avec ta coloc",
      turns: [
        { them: "Ugh, the sink is full. Whose turn is it to do the dishes?", fr: "Pff, l'évier est plein. C'est à qui de faire la vaisselle ?" },
        { you: "Dis que c'est son tour !", answers: ["It's your turn!"] },
        { them: "Fine… Oh, and we're out of milk.", fr: "Bon… Ah, et il n'y a plus de lait." },
        { you: "Dis que tu en rachètes.", answers: ["I'll pick some up.", "No worries, I'll pick some up."] },
        { them: "Thanks! By the way, do you mind if I invite some friends tonight?", fr: "Merci ! Au fait, ça te dérange si j'invite des amis ce soir ?" },
        { you: "Réponds : pas du tout ! Mais demande-lui de ne pas faire trop de bruit.", answers: ["Not at all! Can you keep it down?", "Not at all, but can you keep it down?", "Not at all! Just keep it down, okay?"] },
        { them: "Deal!", fr: "Marché conclu !" },
      ],
    },
  },
  {
    id: "slang",
    char: "sam",
    emoji: "🤙",
    title: "Les expressions de tous les jours",
    intro: "Ces expressions ne sont dans aucun manuel, mais tu les entendras dans toutes les séries et conversations. À utiliser entre amis !",
    phrases: [
      { en: "I'm broke.", fr: "Je suis fauché." },
      { en: "That's a rip-off!", fr: "C'est de l'arnaque !" },
      { en: "Piece of cake.", fr: "Fastoche.", note: "Littéralement « un morceau de gâteau »." },
      { en: "I'm just kidding.", fr: "Je rigole." },
      { en: "Let's hang out.", fr: "On se voit ?", note: "« Hang out » = passer du temps ensemble, sans programme précis." },
      { en: "Hang on.", fr: "Attends deux secondes." },
      { en: "Whatever.", fr: "Peu importe.", note: "Attention : avec un certain ton, ça peut paraître méprisant." },
      { en: "It's not a big deal.", fr: "C'est pas grave." },
    ],
    dialogue: {
      title: "Sam t'appelle",
      turns: [
        { them: "Hey! Let's hang out this weekend. Concert on Saturday?", fr: "Salut ! On se voit ce week-end ? Concert samedi ?" },
        { you: "Demande combien ça coûte.", answers: ["How much is it?"] },
        { them: "A hundred bucks.", fr: "Cent dollars. (bucks = dollars, familier)" },
        { you: "Réagis : c'est de l'arnaque ! Je suis fauché.", answers: ["That's a rip-off! I'm broke."] },
        { them: "Haha, hang on… I'm just kidding, it's free!", fr: "Haha, attends… Je rigole, c'est gratuit !" },
        { you: "Dis : pas possible ! Ça marche !", answers: ["No way! Sounds good!"] },
        { them: "See ya Saturday!", fr: "À samedi !" },
      ],
    },
  },
];
